Multi region parallel update
naris-silpakit/aws-config-rdk pull request #2
Opened 2021-08-02 16:51 UTC by naris-silpakit

2021-08-02 18:56 UTC, jarrettandrulis requested changes

2021-08-02 18:56 UTC, jarrettandrulis commented on rdk/cli.py
> +
We can probably get rid of `confirmation` and add better communication by rewriting this code something similar to:
```python
my_input = input("Delete specified Rules and Lambda Functions from your AWS Account? (y/N): ")
while my_input not in ["y","n"]:
  my_input = input(f"Invalid input: {my_input}. Please enter either 'y' or 'n': ")
if my_input.lower() == "y":
  vars(args)["command_args"].append("--force")
elif my_input.lower() == "n" or my_input == "":
  exit(0)
```

2021-08-02 18:56 UTC, jarrettandrulis commented on rdk/rdk.py
> +    parser.add_argument('-i', '--region-set', help="[optional] Set of regions within the region file with which to run the command in parallel. Looks for a 'default' region set if not specified.")
I think we should remove `-i` for region set and only keep `--region-set` since the two don't really relate

2021-08-02 18:56 UTC, jarrettandrulis commented on rdk/rdk.py
> +        region_text = yaml.load(open(args.region_file, "r"), Loader=yaml.Loader)
We should explore using yaml.SafeLoader, yaml.Loader allows for executing of arbitrary code which we may not want

2021-08-02 18:56 UTC, jarrettandrulis commented on rdk/rdk.py
> +        print (f"[{self.args.region}] Running init!")
Maybe add a colon after the region name for all of these prints so it reads:
`us-east-1: Running init!` rather than `us-east-1 Running init!`

2021-08-02 18:56 UTC, jarrettandrulis commented on testing/multi_region_execution_test.py
> +
I would add a test in here that uses the cloudformation client to verify that the stack has been deployed in the proper regions before undeploying

2021-08-02 18:56 UTC, jarrettandrulis commented on rdk/rdk.py
> +import yaml
Update the requirements.txt file to add yaml as a requirement since it isn't in the default library

2021-08-03 01:14 UTC, naris-silpakit commented on rdk/rdk.py
> +        region_text = yaml.load(open(args.region_file, "r"), Loader=yaml.Loader)
Would `yaml.safe_load()` work?

2021-08-03 01:14 UTC, naris-silpakit commented on rdk/rdk.py
> +        print (f"[{self.args.region}] Running init!")
Updated to `[{self.args.region}]:`

2021-08-03 01:14 UTC, naris-silpakit commented on rdk/rdk.py
> +import yaml
Whoops, done.

2021-08-03 01:15 UTC, naris-silpakit commented on rdk/cli.py
> +
I copied the code from the original undeploy function, but I agree that we can rewrite the code in a better way.

2021-08-03 01:16 UTC, naris-silpakit commented on rdk/rdk.py
> +    parser.add_argument('-i', '--region-set', help="[optional] Set of regions within the region file with which to run the command in parallel. Looks for a 'default' region set if not specified.")
Agreed. I've removed the `-i` flag as an option.

2021-08-03 01:16 UTC, naris-silpakit commented on testing/multi_region_execution_test.py
> +
Will do.

2021-08-11 13:04 UTC, jarrettandrulis approved these changes

2021-08-11 13:04 UTC, merged